  // $67 to $6F unassigned
  KeyStr[IK_KANA]            :='KANA';    (* (Japanese keyboard)            *)
  KeyStr[IK_ABNT_C1]         :='ABNT C1'; (* / ? on Portugese (Brazilian) keyboards *)
  // $74 to $78 unassigned
  KeyStr[IK_CONVERT]         :='CONVERT';    (* (Japanese keyboard)            *)
  // $7A unassigned
  KeyStr[IK_NOCONVERT]       :='NoCONVERT';    (* (Japanese keyboard)            *)
  // $7C unassigned
  KeyStr[IK_YEN]             :='Yen';    (* (Japanese keyboard)            *)
  KeyStr[IK_ABNT_C2]         :='ABNT C2';(* Numpad . on Portugese (Brazilian) keyboards *)
  // $7F to 8C unassigned
  // $8E to $8F unassigned
  KeyStr[IK_CIRCUMFLEX]      :='CIRCUMFLEX';    (* (Japanese keyboard)            *)
  KeyStr[IK_AT]              :='AT';    (*                     (NEC PC98) *)
  KeyStr[IK_COLON]           :='COLON';    (*                     (NEC PC98) *)
  KeyStr[IK_UNDERLINE]       :='UNDERLINE';    (*                     (NEC PC98) *)
  KeyStr[IK_KANJI]           :='KANJI';    (* (Japanese keyboard)            *)
  KeyStr[IK_STOP]            :='STOP';    (*                     (NEC PC98) *)
  KeyStr[IK_AX]              :='AX';    (*                     (Japan AX) *)
  KeyStr[IK_UNLABELED]       :='---';    (*                        (J3100) *)
  // $98 unassigned
  KeyStr[IK_NEXTTRACK]       :='NEXT';    (* Next Track *)
  // $9A to $9D unassigned
  KeyStr[IK_RCONTROL]        :='RCTRL';
  // $9E to $9F unassigned
  KeyStr[IK_MUTE]            :='MUTE';    (* Mute *)
  KeyStr[IK_CALCULATOR]      :='CALC';    (* Calculator *)
  KeyStr[IK_PLAYPAUSE]       :='Play/Pause';    (* Play / Pause *)
  KeyStr[IK_MEDIASTOP]       :='Media Stop';    (* Media Stop *)
  // $A5 to $AD unassigned
  KeyStr[IK_VOLUMEDOWN]      :='V<';    (* Volume - *)
  // $AF unassigned
  KeyStr[IK_VOLUMEUP]        :='V>';    (* Volume + *)
  // $B1 unassigned
  KeyStr[IK_WEBHOME]         :='Web Home';    (* Web home *)
  KeyStr[IK_NUMPADCOMMA]     :='NumPad Comma';    (* , on numeric keypad (NEC PC98) *)
  // $B4 unassigned
  KeyStr[IK_DIVIDE]          :='/';    (* / on numeric keypad *)
  // $B6 unassigned
  KeyStr[IK_SYSRQ]           :='SysReq';
  KeyStr[IK_RMENU]           :='RAlt';    (* right Alt *)
  // $B9 to $C4 unassigned
  KeyStr[IK_PAUSE]           :='Pause';     (* Pause (watch out - not realiable on some kbds) *)
  // $C6 unassigned
  KeyStr[IK_HOME]            :='Home';     (* Home on arrow keypad *)
  KeyStr[IK_UP]              :='Up';     (* UpArrow on arrow keypad *)
  KeyStr[IK_PRIOR]           :='PgUp';     (* PgUp on arrow keypad *)
  // $CA unassigned
  KeyStr[IK_LEFT]            :='Left';     (* LeftArrow on arrow keypad *)
  // $CC unassigned
  KeyStr[IK_RIGHT]           :='Right';     (* RightArrow on arrow keypad *)
  // $CE unassigned
  KeyStr[IK_END]             :='End';     (* End on arrow keypad *)
  KeyStr[IK_DOWN]            :='Down';     (* DownArrow on arrow keypad *)
  KeyStr[IK_NEXT]            :='PgDn';     (* PgDn on arrow keypad *)
  KeyStr[IK_INSERT]          :='Insert';     (* Insert on arrow keypad *)
  KeyStr[IK_DELETE]          :='Delete';     (* Delete on arrow keypad *)
  KeyStr[IK_LOS]             :='LOS';     (* Left Windows key *)
  KeyStr[IK_ROS]             :='ROS';     (* Right Windows key *)
  KeyStr[IK_APPS]            :='Apps';     (* AppMenu key *)
  KeyStr[IK_POWER]           :='Power';
  KeyStr[IK_SLEEP]           :='Sleep';
  // $E0 to $E2 unassigned
  KeyStr[IK_WAKE]            :='Wake';    (* System Wake *)
  // $E4 unassigned
  KeyStr[IK_WEBSEARCH]       :='Web Search';    (* Web Search *)
  KeyStr[IK_WEBFAVORITES]    :='Web Fav';    (* Web Favorites *)
  KeyStr[IK_WEBREFRESH]      :='Web Refresh';    (* Web Refresh *)
  KeyStr[IK_WEBSTOP]         :='Web Stop';    (* Web Stop *)
  KeyStr[IK_WEBFORWARD]      :='Web Forward';    (* Web Forward *)
  KeyStr[IK_WEBBACK]         :='Web Back';    (* Web Back *)
  KeyStr[IK_MYCOMPUTER]      :='My Computer';    (* My Computer *)
  KeyStr[IK_MAIL]            :='Mail';    (* Mail *)
  KeyStr[IK_MEDIASELECT]     :='Media Select';    (* Media Select *)

  // Main 
  KeyStr[IK_ESCAPE]          :='ESC';
  KeyStr[IK_1]               :='1';
  KeyStr[IK_2]               :='2';
  KeyStr[IK_3]               :='3';
  KeyStr[IK_4]               :='4';
  KeyStr[IK_5]               :='5';
  KeyStr[IK_6]               :='6';
  KeyStr[IK_7]               :='7';
  KeyStr[IK_8]               :='8';
  KeyStr[IK_9]               :='9';
  KeyStr[IK_0]               :='0';
  KeyStr[IK_MINUS]           :='-';    (* - on main keyboard *)
  KeyStr[IK_EQUALS]          :='=';
  KeyStr[IK_BACK]            :='BkSp'; (* backspace *)
  KeyStr[IK_TAB]             :='Tab';
  KeyStr[IK_Q]               :='Q';
  KeyStr[IK_W]               :='W';
  KeyStr[IK_E]               :='E';
  KeyStr[IK_R]               :='R';
  KeyStr[IK_T]               :='T';
  KeyStr[IK_Y]               :='Y';
  KeyStr[IK_U]               :='U';
  KeyStr[IK_I]               :='I';
  KeyStr[IK_O]               :='O';
  KeyStr[IK_P]               :='P';
  KeyStr[IK_LBRACKET]        :='[';
  KeyStr[IK_RBRACKET]        :=']';
  KeyStr[IK_NUMPADEQUALS]    :='Gray ENTER';     (* :=on numeric keypad (NEC PC98) *)
  KeyStr[IK_NUMPADENTER]     :='Gray ENTER';     (* Enter on numeric keypad *)
  KeyStr[IK_RETURN]          :='ENTER';     (* Enter on main keyboard *)
  KeyStr[IK_LCONTROL]        :='LCTRL';
  KeyStr[IK_A]               :='A';
  KeyStr[IK_S]               :='S';
  KeyStr[IK_D]               :='D';
  KeyStr[IK_F]               :='F';
  KeyStr[IK_G]               :='G';
  KeyStr[IK_H]               :='H';
  KeyStr[IK_J]               :='J';
  KeyStr[IK_K]               :='K';
  KeyStr[IK_L]               :='L';
  KeyStr[IK_SEMICOLON]       :=';';
  KeyStr[IK_APOSTROPHE]      :='''';
  KeyStr[IK_GRAVE]           :='`'; //$29;    (* accent grave *)
  KeyStr[IK_LSHIFT]          :='LShift';
  KeyStr[IK_BACKSLASH]       :='\';
  KeyStr[IK_Z]               :='Z';
  KeyStr[IK_X]               :='X';
  KeyStr[IK_C]               :='C';
  KeyStr[IK_V]               :='V';
  KeyStr[IK_B]               :='B';
  KeyStr[IK_N]               :='N';
  KeyStr[IK_M]               :='M';
  KeyStr[IK_COMMA]           :='Comma';
  KeyStr[IK_PERIOD]          :='Period';    (* . on main keyboard *)
  KeyStr[IK_SLASH]           :='/';    (* / on main keyboard *)
  KeyStr[IK_RSHIFT]          :='RShift';
  KeyStr[IK_MULTIPLY]        :='Gray *';    (* * on numeric keypad *)
  KeyStr[IK_LMENU]           :='LAlt';    (* left Alt *)
  KeyStr[IK_SPACE]           :='SPACE';
  KeyStr[IK_CAPITAL]         :='CAPS';
  KeyStr[IK_F1]              :='F1';
  KeyStr[IK_F2]              :='F2';
  KeyStr[IK_F3]              :='F3';
  KeyStr[IK_F4]              :='F4';
  KeyStr[IK_F5]              :='F5';
  KeyStr[IK_F6]              :='F6';
  KeyStr[IK_F7]              :='F7';
  KeyStr[IK_F8]              :='F8';
  KeyStr[IK_F9]              :='F9';
  KeyStr[IK_F10]             :='F10';
  KeyStr[IK_NUMLOCK]         :='NUM';
  KeyStr[IK_SCROLL]          :='SCROLL';      (* Scroll Lock *)
  KeyStr[IK_NUMPAD7]         :='KeyPad 7';
  KeyStr[IK_NUMPAD8]         :='KeyPad 8';
  KeyStr[IK_NUMPAD9]         :='KeyPad 9';
  KeyStr[IK_SUBTRACT]        :='Gray Minus';    (* - on numeric keypad *)
  KeyStr[IK_NUMPAD4]         :='KeyPad 4';
  KeyStr[IK_NUMPAD5]         :='KeyPad 5';
  KeyStr[IK_NUMPAD6]         :='KeyPad 6';
  KeyStr[IK_ADD]             :='Gray Plus';    (* + on numeric keypad *)
  KeyStr[IK_NUMPAD1]         :='KeyPad 1';
  KeyStr[IK_NUMPAD2]         :='KeyPad 2';
  KeyStr[IK_NUMPAD3]         :='KeyPad 3';
  KeyStr[IK_NUMPAD0]         :='KeyPad 0';
  KeyStr[IK_DECIMAL]         :='Decimal';    (* . on numeric keypad *)
  // $54 to $55 unassigned
  KeyStr[IK_OEM_102]         :='OEM 102';    (* < > | on UK/Germany keyboards *)
  KeyStr[IK_F11]             :='F11';
  KeyStr[IK_F12]             :='F12';
  // $59 to $63 unassigned
  KeyStr[IK_F13]             :='F13';    (*                     (NEC PC98) *)
  KeyStr[IK_F14]             :='F14';    (*                     (NEC PC98) *)
  KeyStr[IK_F15]             :='F15';    (*                     (NEC PC98) *)
(*
 *  Alternate names for keys, to facilitate transition from DOS.
 *)
  KeyStr[IK_BACKSPACE]      :='BkSp';      (* backspace *)
  KeyStr[IK_NUMPADSTAR]     :='Gray *';  (* * on numeric keypad *)
  KeyStr[IK_LALT]           :='LAlt';     (* left Alt *)
  KeyStr[IK_CAPSLOCK]       :='CAPS';   (* CapsLock *)
  KeyStr[IK_NUMPADMINUS]    :='Gray Minus';  (* - on numeric keypad *)
  KeyStr[IK_NUMPADPLUS]     :='Gray Plus';       (* + on numeric keypad *)
  KeyStr[IK_NUMPADPERIOD]   :='Decimal';   (* . on numeric keypad *)
  KeyStr[IK_NUMPADSLASH]    :='Gray /';    (* / on numeric keypad *)
  KeyStr[IK_RALT]           :='RAlt';     (* right Alt *)
  KeyStr[IK_UPARROW]        :='Up';        (* UpArrow on arrow keypad *)
  KeyStr[IK_PGUP]           :='PgUp';     (* PgUp on arrow keypad *)
  KeyStr[IK_LEFTARROW]      :='Left';      (* LeftArrow on arrow keypad *)
  KeyStr[IK_RIGHTARROW]     :='Right';     (* RightArrow on arrow keypad *)
  KeyStr[IK_DOWNARROW]      :='Down';      (* DownArrow on arrow keypad *)
  KeyStr[IK_PGDN]           :='PgDn';      (* PgDn on arrow keypad *)

(*
 *  Alternate names for keys originally not used on US keyboards.
 *)

  KeyStr[IK_PREVTRACK]      :='CIRCUMFLEX';  (* Japanese keyboard *)

  KeyStr[IK_MOUSELEFT]       :='LMB';
  KeyStr[IK_MOUSERIGHT]      :='RMB';
  KeyStr[IK_MOUSEMIDDLE]     :='MMB';

  KeyStr[IK_SHIFT]           :='Shift';
  KeyStr[IK_CONTROL]         :='CTRL';
  KeyStr[IK_ALT]             :='Alt';